In [1]:
import pandas as pd

df = pd.read_csv('../data/flood.csv')

df.head()

,MonsoonIntensity,TopographyDrainage,RiverManagement,Deforestation,Urbanization,ClimateChange,DamsQuality,Siltation,AgriculturalPractices,Encroachments,...,DrainageSystems,CoastalVulnerability,Landslides,Watersheds,DeterioratingInfrastructure,PopulationScore,WetlandLoss,InadequatePlanning,PoliticalFactors,FloodProbability
0,3,8,6,6,4,4,6,2,3,2,...,10,7,4,2,3,4,3,2,6,0.450
1,8,4,5,7,7,9,1,5,5,4,...,9,2,6,2,1,1,9,1,3,0.475
2,3,10,4,1,7,5,4,7,4,9,...,7,4,4,8,6,1,8,3,6,0.515
3,4,4,2,7,3,4,1,4,6,4,...,4,2,6,6,8,8,6,6,10,0.520
4,3,7,5,2,5,8,5,2,7,5,...,7,6,5,3,3,4,4,3,4,0.475

In [2]:
df.shape

(50000, 21)

In [3]:
df.dtypes

MonsoonIntensity                     int64
TopographyDrainage                   int64
RiverManagement                      int64
Deforestation                        int64
Urbanization                         int64
ClimateChange                        int64
DamsQuality                          int64
Siltation                            int64
AgriculturalPractices                int64
Encroachments                        int64
IneffectiveDisasterPreparedness      int64
DrainageSystems                      int64
CoastalVulnerability                 int64
Landslides                           int64
Watersheds                           int64
DeterioratingInfrastructure          int64
PopulationScore                      int64
WetlandLoss                          int64
InadequatePlanning                   int64
PoliticalFactors                     int64
FloodProbability                   float64
dtype: object

In [4]:
print("Dataset has no null values:", df.isnull().sum().sum() == 0)

Dataset has no null values: True

In [5]:
df.describe(include="all").T

,count,mean,std,min,25%,50%,75%,max
MonsoonIntensity,50000.0,4.99148,2.236834,0.000,3.000,5.0,6.000,16.000
TopographyDrainage,50000.0,4.98410,2.246488,0.000,3.000,5.0,6.000,18.000
RiverManagement,50000.0,5.01594,2.231310,0.000,3.000,5.0,6.000,16.000
Deforestation,50000.0,5.00848,2.222743,0.000,3.000,5.0,6.000,17.000
Urbanization,50000.0,4.98906,2.243159,0.000,3.000,5.0,6.000,17.000
ClimateChange,50000.0,4.98834,2.226761,0.000,3.000,5.0,6.000,17.000
DamsQuality,50000.0,5.01536,2.245000,0.000,3.000,5.0,6.000,16.000
Siltation,50000.0,4.98860,2.232642,0.000,3.000,5.0,6.000,16.000
AgriculturalPractices,50000.0,5.00612,2.234588,0.000,3.000,5.0,6.000,16.000
Encroachments,50000.0,5.00638,2.241633,0.000,3.000,5.0,6.000,18.000
IneffectiveDisasterPreparedness,50000.0,5.00502,2.226076,0.000,3.000,5.0,6.000,16.000
DrainageSystems,50000.0,5.00606,2.238107,0.000,3.000,5.0,6.000,17.000
CoastalVulnerability,50000.0,4.99992,2.247101,0.000,3.000,5.0,6.000,17.000
Landslides,50000.0,4.98422,2.227741,0.000,3.000,5.0,6.000,16.000
Watersheds,50000.0,4.97982,2.232190,0.000,3.000,5.0,6.000,16.000
DeterioratingInfrastructure,50000.0,4.98820,2.231134,0.000,3.000,5.0,6.000,17.000
PopulationScore,50000.0,4.98498,2.238279,0.000,3.000,5.0,6.000,19.000
WetlandLoss,50000.0,5.00512,2.231760,0.000,3.000,5.0,6.000,22.000
InadequatePlanning,50000.0,4.99436,2.230011,0.000,3.000,5.0,6.000,16.000
PoliticalFactors,50000.0,4.99052,2.246075,0.000,3.000,5.0,6.000,16.000
FloodProbability,50000.0,0.49966,0.050034,0.285,0.465,0.5,0.535,0.725

In [6]:
df["FloodProbability"].value_counts(dropna=False)

FloodProbability
0.500    2018
0.490    1984
0.495    1975
0.485    1960
0.505    1945
         ...
0.710       1
0.700       1
0.715       1
0.285       1
0.725       1
Name: count, Length: 83, dtype: int64